sudo: required
dist: trusty

# stages:
#   - test
#   - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  - pushd "$(haxe --run resolve-args -lib linc_uv | grep /linc_uv/)/lib" # clone submodules
  - rm -rf libuv && git clone https://github.com/libuv/libuv
  - popd
  
script:
  - lix run travix cpp -lib linc_uv --no-traces -D NO_PRECOMPILED_HEADERS
